---
title: "Hydrological indicator calculations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Hydrological indicator calculations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In this vignette, we compute all available numerical hydrological indicators
available in CARD scripts.

```{r setup}
library(EXstat)
library(dplyr)
library(tidyr)
```

Import data:

```{r read-data}
df <- readr::read_tsv(
  system.file("examples", "Aqui-FR-Qnat.tsv", package = "EXstat")
)
```

Format data in tidy format:

```{r tidy-format}
dfQ <- df |> pivot_longer(!"date", values_to = "Q")
dfQ
```

```{r card-management}
CARD_dir <- "analysis1"
CARD_name = c("QMNA-5", "BFI_Wal")
CARD_tmp <- CARD_management(
  CARD_dir = CARD_dir,
  CARD_name = CARD_name,
  verbose = TRUE
)
```

```{r card-extraction1}
results <- CARD_extraction(
  data = dfQ,
  CARD_tmp = CARD_tmp,
  CARD_dir = CARD_dir,
  simplify = TRUE,
  verbose = FALSE
)
results
```

```{r card-name}
CARD_path <- system.file("CARD", package = "EXstat")
CARD_dir <- "__all__/Flow"
CARD_dirpath = file.path(CARD_path, CARD_dir)
script_to_analyse = list.files(
        path = CARD_dirpath,
        pattern = "\\.R$",
        recursive = TRUE,
        include.dirs = FALSE,
        full.names = FALSE
    )
script_to_analyse <- script_to_analyse[grepl("criteria", script_to_analyse)]
CARD_name <- gsub("\\.R$", "", basename(script_to_analyse))
# Remove indicators linked to Explore2 horizons
CARD_name <- CARD_name[!grepl("_H[0-3]*$", CARD_name)]
# Remove indicators that can't be computed (Qobs/Qsim comparisons)
CARD_name <- CARD_name[!grepl("Bias|KGE|NSE|STD", CARD_name)]
# Remove indicators that return logical
CARD_name <- CARD_name[!grepl("alpha", CARD_name)]
# Remove bugged indicators
CARD_name <- CARD_name[!CARD_name %in% c("med{dtRec}")]

```

```{r card-extraction2}
results <- CARD_extraction(
  data = dfQ,
  CARD_name = CARD_name,
  simplify = TRUE,
  verbose = FALSE
)
results
```

```{r format-result}
metaEX <- results$metaEX |> select("variable_en", "name_en", "unit_en")
dataEX <- metaEX |> 
  left_join(CARD_transpose_data(results$dataEX),
            by = join_by("variable_en" == "name")) |>
  mutate(unit_en = sprintf("$\\mathrm{%s}$", unit_en))
knitr::kable(dataEX, escape = FALSE)
```
